version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: hyperclean_mysql
    restart: unless-stopped
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'hyperclean'
      TZ: 'UTC'
    command: mysqld --innodb-buffer-pool-size=3072M --innodb_log_file_size=1024M --innodb_log_buffer_size=5M --sql_mode="TIME_TRUNCATE_FRACTIONAL" --max-connections=5000 --max-user-connections=5000
    volumes:
      - hyperclean_mysql_data:/var/lib/mysql

  memcached:
    image: memcached
    container_name: hyperclean_memcached
    command: [ "-I","20m" ]
    restart: unless-stopped
    ports:
      - 11211:11211
    networks:
      - hyperclean_network

volumes:
  hyperclean_mysql_data:
    name: hyperclean_mysql_data

networks:
  hyperclean_network:
    name: hyperclean_network